#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npx prettier --write .

# Check Prettier standards
npm run check-format ||
(
    echo 'Your code is not pretty enough 😵📉
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'Your code is not linted enough 🚫
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# If everything passes... validate branch name
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|fix|hotfix|release)\/[a-z0-9._-]+$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex."

(
if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "Invalid branch name  ❌
        $message"
    exit 1
fi
)

# If everything passes... Now we can commit
echo 'Alright... Code looks good to me... Trying to build now... 🏗️👷'

npm run build ||
(
    echo 'Better call Bob... Because your build failed 👷🔨
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo 'congratulations your code is clean. I am committing this now. ✅✅✅✅'
